# coding: utf-8

"""
    Adobe Target Delivery API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Address(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'url': 'str',
        'referring_url': 'str'
    }

    attribute_map = {
        'url': 'url',
        'referring_url': 'referringUrl'
    }

    def __init__(self, url=None, referring_url=None):
        """Address - a model defined in OpenAPI"""

        self._url = None
        self._referring_url = None
        self.discriminator = None

        if url is not None:
            self.url = url
        if referring_url is not None:
            self.referring_url = referring_url

    @property
    def url(self):
        """Gets the url of this Address.

        URL

        :return: The url of this Address.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Address.

        URL

        :param url: The url of this Address.
        :type: str
        """
        if url is not None and len(url) > 4096:
            raise ValueError("Invalid value for `url`, length must be less than or equal to `4096`")

        self._url = url

    @property
    def referring_url(self):
        """Gets the referring_url of this Address.

        referral URL

        :return: The referring_url of this Address.
        :rtype: str
        """
        return self._referring_url

    @referring_url.setter
    def referring_url(self, referring_url):
        """Sets the referring_url of this Address.

        referral URL

        :param referring_url: The referring_url of this Address.
        :type: str
        """
        if referring_url is not None and len(referring_url) > 4096:
            raise ValueError("Invalid value for `referring_url`, length must be less than or equal to `4096`")

        self._referring_url = referring_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Address):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
