# coding: utf-8

"""
    Adobe Target Delivery API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ExperienceCloud(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'audience_manager': 'AudienceManager',
        'analytics': 'AnalyticsRequest'
    }

    attribute_map = {
        'audience_manager': 'audienceManager',
        'analytics': 'analytics'
    }

    def __init__(self, audience_manager=None, analytics=None):
        """ExperienceCloud - a model defined in OpenAPI"""

        self._audience_manager = None
        self._analytics = None
        self.discriminator = None

        if audience_manager is not None:
            self.audience_manager = audience_manager
        if analytics is not None:
            self.analytics = analytics

    @property
    def audience_manager(self):
        """Gets the audience_manager of this ExperienceCloud.


        :return: The audience_manager of this ExperienceCloud.
        :rtype: AudienceManager
        """
        return self._audience_manager

    @audience_manager.setter
    def audience_manager(self, audience_manager):
        """Sets the audience_manager of this ExperienceCloud.


        :param audience_manager: The audience_manager of this ExperienceCloud.
        :type: AudienceManager
        """

        self._audience_manager = audience_manager

    @property
    def analytics(self):
        """Gets the analytics of this ExperienceCloud.


        :return: The analytics of this ExperienceCloud.
        :rtype: AnalyticsRequest
        """
        return self._analytics

    @analytics.setter
    def analytics(self, analytics):
        """Sets the analytics of this ExperienceCloud.


        :param analytics: The analytics of this ExperienceCloud.
        :type: AnalyticsRequest
        """

        self._analytics = analytics

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExperienceCloud):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
