# coding: utf-8

"""
    Adobe Target Delivery API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class NotificationResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'trace': 'dict(str, object)'
    }

    attribute_map = {
        'id': 'id',
        'trace': 'trace'
    }

    def __init__(self, id=None, trace=None):
        """NotificationResponse - a model defined in OpenAPI"""

        self._id = None
        self._trace = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if trace is not None:
            self.trace = trace

    @property
    def id(self):
        """Gets the id of this NotificationResponse.

        Notification id which indicates that the notification was processed successfully. 

        :return: The id of this NotificationResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this NotificationResponse.

        Notification id which indicates that the notification was processed successfully. 

        :param id: The id of this NotificationResponse.
        :type: str
        """

        self._id = id

    @property
    def trace(self):
        """Gets the trace of this NotificationResponse.

        The object containing all trace data for the request, only present if the trace token was provided in the request. 

        :return: The trace of this NotificationResponse.
        :rtype: dict(str, object)
        """
        return self._trace

    @trace.setter
    def trace(self, trace):
        """Sets the trace of this NotificationResponse.

        The object containing all trace data for the request, only present if the trace token was provided in the request. 

        :param trace: The trace of this NotificationResponse.
        :type: dict(str, object)
        """

        self._trace = trace

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NotificationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
