# coding: utf-8

"""
    Adobe Target Delivery API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class TelemetryFeatures(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'decisioning_method': 'DecisioningMethod'
    }

    attribute_map = {
        'decisioning_method': 'decisioningMethod'
    }

    def __init__(self, decisioning_method=None):
        """TelemetryFeatures - a model defined in OpenAPI"""

        self._decisioning_method = None
        self.discriminator = None

        if decisioning_method is not None:
            self.decisioning_method = decisioning_method

    @property
    def decisioning_method(self):
        """Gets the decisioning_method of this TelemetryFeatures.


        :return: The decisioning_method of this TelemetryFeatures.
        :rtype: DecisioningMethod
        """
        return self._decisioning_method

    @decisioning_method.setter
    def decisioning_method(self, decisioning_method):
        """Sets the decisioning_method of this TelemetryFeatures.


        :param decisioning_method: The decisioning_method of this TelemetryFeatures.
        :type: DecisioningMethod
        """

        self._decisioning_method = decisioning_method

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TelemetryFeatures):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
