name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@main
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: lint, test, build
        env:
          CI: true
          PYTHON_PATH: python
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          make pre_build
      - run: echo "COVERALLS_SUPPORTED=3.9" >> $GITHUB_ENV
      - if: contains(env.COVERALLS_SUPPORTED, matrix.python-version)
        name: generate coveralls coverage
        run: coveralls debug --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
          COVERALLS_PARALLEL: false
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
