name: Upload Python Package

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Bump which version number? (major, minor, patch)"
        required: true
        default: "patch"

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '^3.9'
    - name: Install dependencies
      env:
        CI: true
        PYTHON_PATH: python
        PYTHON_VERSION: 3.9
      run: |
        make pre_build
    - name: Build and publish new version
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        CI: true
        PYTHON_PATH: python
      run: |
        git config --global user.email "target-python-sdk-release@adobe.com"
        git config --global user.name "target-python-sdk release bot"
        make version_bump part=${{ github.event.inputs.bump }}
        make build
        make publish
